using System;
using System.Collections.Generic;

namespace Ef5Data.Models
{
    public class TIPProjectEvaluation2010
    {
        public TIPProjectEvaluation2010()
        {
            this.Features = new List<Feature>();
            this.TIPProjectEvaluation2010Mode = new List<TIPProjectEvaluation2010Mode>();
        }

        public int ProjectVersionID { get; set; }
        public Nullable<double> PCI { get; set; }
        public Nullable<double> PavementConditionScore { get; set; }
        public Nullable<double> TotalScore { get; set; }
        public Nullable<double> SafetyScore { get; set; }
        public Nullable<int> FatalCrashes { get; set; }
        public Nullable<int> InjuryCrashes { get; set; }
        public Nullable<int> PDOCrashes { get; set; }
        public Nullable<int> AccidentsReduced { get; set; }
        public string ServiceType { get; set; }
        public string SecondaryServiceType { get; set; }
        public Nullable<int> AWDT { get; set; }
        public Nullable<int> AWDT2 { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<int> NumberOfLanes { get; set; }
        public Nullable<double> UsageScore { get; set; }
        public Nullable<double> CEScore { get; set; }
        public Nullable<double> VOverC { get; set; }
        public Nullable<double> CongestionScore { get; set; }
        public Nullable<double> PriorityScore { get; set; }
        public Nullable<double> VHT { get; set; }
        public Nullable<double> ContinuityScore { get; set; }
        public Nullable<double> MetroVisionProjectScore { get; set; }
        public Nullable<bool> PlanImplementation { get; set; }
        public Nullable<bool> EmphasizedRoadway { get; set; }
        public Nullable<double> Usage { get; set; }
        public string SpeedLimit { get; set; }
        public Nullable<bool> InsufficientLight { get; set; }
        public Nullable<bool> ImprovedLight { get; set; }
        public Nullable<double> VMT { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> AddedAWDT { get; set; }
        public Nullable<bool> Intersection { get; set; }
        public Nullable<double> Length2 { get; set; }
        public Nullable<decimal> Subsidy { get; set; }
        public string UsageSupport { get; set; }
        public Nullable<double> UsageSupportScore { get; set; }
        public Nullable<bool> BusMarketing { get; set; }
        public Nullable<bool> BusPedAccess { get; set; }
        public Nullable<bool> BusCostReduction { get; set; }
        public string PedAccessAction1 { get; set; }
        public string PedAccessAction2 { get; set; }
        public string CostReductionAction1 { get; set; }
        public string CostReductionAction2 { get; set; }
        public Nullable<double> RegionalRelevanceScore { get; set; }
        public string EligibleCapacityProject { get; set; }
        public string BikeAndPedSubtype { get; set; }
        public Nullable<double> PotentialNeedScore { get; set; }
        public string AQImprovementMethod { get; set; }
        public Nullable<double> BenefitScore { get; set; }
        public Nullable<int> BenefitFeatureTypeID { get; set; }
        public Nullable<int> VHTReduction { get; set; }
        public Nullable<int> VMTReduction { get; set; }
        public Nullable<int> ReductionInPounds { get; set; }
        public string PollutantType { get; set; }
        public Nullable<int> NetReductionInPounds { get; set; }
        public Nullable<bool> LongTermFunding { get; set; }
        public Nullable<double> LongTermFundingScore { get; set; }
        public Nullable<bool> ProvidesMedians { get; set; }
        public Nullable<bool> ImprovesAccessControl { get; set; }
        public Nullable<bool> ProvidesLeftTurns { get; set; }
        public Nullable<bool> ImprovesSignalInterconnection { get; set; }
        public Nullable<bool> ProvidesITS { get; set; }
        public Nullable<double> TSMScore { get; set; }
        public Nullable<bool> MMCTransitOps { get; set; }
        public Nullable<bool> MMCTransitAmenities { get; set; }
        public Nullable<bool> MMCBikeLanes { get; set; }
        public Nullable<bool> MMCGradeSeparation { get; set; }
        public Nullable<bool> MMCBikeAmenities { get; set; }
        public Nullable<bool> MMCPedLinks { get; set; }
        public Nullable<bool> MMCSignalPriority { get; set; }
        public Nullable<bool> MMCParking { get; set; }
        public Nullable<bool> MMCTMO { get; set; }
        public Nullable<bool> MMCTelework { get; set; }
        public Nullable<bool> MMCRoadwayOps { get; set; }
        public Nullable<bool> MMCITS { get; set; }
        public Nullable<bool> MMCBikeLinks { get; set; }
        public Nullable<bool> MMCShuttles { get; set; }
        public Nullable<bool> MMCConnections { get; set; }
        public Nullable<bool> MMCServiceGap { get; set; }
        public Nullable<bool> MMCRoutes { get; set; }
        public Nullable<bool> MMCFutureFacilities { get; set; }
        public Nullable<double> MultiModalScore { get; set; }
        public Nullable<bool> MMCRoutes2 { get; set; }
        public Nullable<double> MetroVisionScore { get; set; }
        public Nullable<double> OvermatchScore { get; set; }
        public string ProjectLocationForPM10 { get; set; }
        public Nullable<double> PM10Score { get; set; }
        public Nullable<double> BenefitYears { get; set; }
        public string EmphasisType { get; set; }
        public Nullable<double> PMT { get; set; }
        public string GapClosureMeasure { get; set; }
        public string PedCrossingMeasure { get; set; }
        public Nullable<bool> BidirectionalUse { get; set; }
        public Nullable<bool> BikePedNetworkConnections { get; set; }
        public Nullable<bool> BarrierElimination { get; set; }
        public Nullable<bool> AccessToTransit { get; set; }
        public Nullable<int> Lockers { get; set; }
        public Nullable<bool> ScenicEasements { get; set; }
        public Nullable<bool> RailsToTrails { get; set; }
        public Nullable<bool> ScenicBeautification { get; set; }
        public Nullable<int> ReductionInPoundsAll { get; set; }
        public Nullable<short> ConformityCommitmentPoints { get; set; }
        public Nullable<short> currentpracticepoints { get; set; }
        public Nullable<short> PriorityCorridorsBikePed { get; set; }
        public string PriorityCorridorsBikePedProjectType { get; set; }
        public string BikePedConnectivityGapClosure { get; set; }
        public string BikePedConnectivityAccess { get; set; }
        public string BikePedConnectivityBarrierElimination { get; set; }
        public string BikePedConnectivityTransit { get; set; }
        public Nullable<double> ConnectivityScore { get; set; }
        public Nullable<bool> BikePedBidirectionalUse { get; set; }
        public Nullable<short> LockersOrRacksPoints { get; set; }
        public Nullable<bool> BikePedAcquiringScenicEasements { get; set; }
        public Nullable<bool> BikePedRailsToTrails { get; set; }
        public Nullable<double> MultipleEnhancementsScore { get; set; }
        public string WithinUrbanCenter { get; set; }
        public Nullable<bool> DIA { get; set; }
        public string StrategicCorridors { get; set; }
        public string BusServiceClass { get; set; }
        public Nullable<short> ProvidesIncidentManagement { get; set; }
        public Nullable<bool> FutureTransitFacilities { get; set; }
        public Nullable<bool> TransitAmenities { get; set; }
        public Nullable<bool> BuildingNewPath { get; set; }
        public Nullable<bool> BikeAmenities { get; set; }
        public Nullable<bool> PedestrianLinks { get; set; }
        public Nullable<bool> IncorporatingTransit { get; set; }
        public Nullable<bool> TransitOperationalFeatures { get; set; }
        public Nullable<double> RidershipPotentialScore { get; set; }
        public Nullable<int> RidershipPotential { get; set; }
        public Nullable<double> PercentBrownfields { get; set; }
        public Nullable<double> PercentInfillRedevelopment { get; set; }
        public Nullable<double> PercentLowIncome { get; set; }
        public Nullable<double> ExistingStationScore { get; set; }
        public Nullable<double> OtherCriticalityCriteriaScore { get; set; }
        public Nullable<double> ConditionMajorStructureScore { get; set; }
        public Nullable<double> RTPScore { get; set; }
        public Nullable<double> BridgeScore { get; set; }
        public Nullable<double> PMTCostBus { get; set; }
        public Nullable<double> PMTCostInterchange { get; set; }
        public Nullable<double> WeightedCrashRate { get; set; }
        public string EmphasisCorridors { get; set; }
        public Nullable<bool> ImplementFastracks { get; set; }
        public Nullable<double> LongRangePlanScore { get; set; }
        public Nullable<bool> MetroVisionMeasuresProject { get; set; }
        public string ExistingFacilitiesDescription { get; set; }
        public Nullable<double> RTPLongRangePlanScore { get; set; }
        public Nullable<short> NumPropertyOwners { get; set; }
        public Nullable<double> CurrentCongestionScore { get; set; }
        public string NameOfQualifiedTrafficEngineer { get; set; }
        public Nullable<bool> mmcpedstreetlighting { get; set; }
        public Nullable<bool> mmcstreettrees { get; set; }
        public Nullable<bool> mmcdetaching { get; set; }
        public string withinugb { get; set; }
        public Nullable<bool> DieselRetrofitProject { get; set; }
        public Nullable<short> ProjectTypeScore { get; set; }
        public Nullable<bool> newconstructionproject { get; set; }
        public Nullable<bool> compliantlighting { get; set; }
        public Nullable<bool> AdditionalAmenities { get; set; }
        public Nullable<short> NumRacks { get; set; }
        public Nullable<short> NumLockers { get; set; }
        public Nullable<bool> VOC { get; set; }
        public Nullable<bool> PM10 { get; set; }
        public Nullable<bool> CO { get; set; }
        public Nullable<bool> NOX { get; set; }
        public Nullable<float> ReductionInPounds_VOC { get; set; }
        public Nullable<float> ReductionInPounds_PM10 { get; set; }
        public Nullable<float> ReductionInPounds_CO { get; set; }
        public Nullable<float> ReductionInPounds_NOX { get; set; }
        public string bikepedconnectivitylocation { get; set; }
        public Nullable<bool> PM2Point5 { get; set; }
        public Nullable<float> ReductionInPounds_PM2Point5 { get; set; }
        public Nullable<short> Users { get; set; }
        public Nullable<double> ExistingUsersScore { get; set; }
        public Nullable<bool> EightPercentOrGreaterGrade { get; set; }
        public Nullable<bool> SubstandardRadiiImproved { get; set; }
        public Nullable<bool> SubstandardSightDistanceImproved { get; set; }
        public Nullable<bool> NARROWPATHINCREASED { get; set; }
        public Nullable<bool> ExistingCompliantLighting { get; set; }
        public Nullable<long> ProjectCost { get; set; }
        public string StudiesProjectType { get; set; }
        public string Temp_ResubmitReadyStatus { get; set; }
        public Nullable<bool> NonCOGMoney { get; set; }
        public Nullable<float> PercentOfProjectInEJ { get; set; }
        public string CommunityBenefits { get; set; }
        public string SupportingEvidence { get; set; }
        public Nullable<float> EJScore { get; set; }
        public Nullable<float> AMVHTReduced { get; set; }
        public Nullable<float> PMVHTReduced { get; set; }
        public Nullable<float> DelayReductionScore { get; set; }
        public Nullable<float> SOVPercentageDecrease { get; set; }
        public Nullable<float> MultimodalPotentialScore { get; set; }
        public Nullable<bool> MinorMMCTransitOps { get; set; }
        public Nullable<bool> MajorMMCTransitOps { get; set; }
        public Nullable<bool> MMCWidening { get; set; }
        public Nullable<bool> Mmcbikepriority { get; set; }
        public Nullable<bool> Mmcprotectedcrossing { get; set; }
        public Nullable<bool> Mmctravellane { get; set; }
        public Nullable<float> GHGScore { get; set; }
        public Nullable<bool> BikePedAddsBikeSpaces { get; set; }
        public Nullable<bool> BikePedAddsCoveredBikeSpaces { get; set; }
        public virtual ICollection<Feature> Features { get; set; }
        public virtual ICollection<TIPProjectEvaluation2010Mode> TIPProjectEvaluation2010Mode { get; set; }
    }
}
