//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("OmbudsmanModel", "FK_dbo_Facilities_dbo_FacilityTypes_FacilityTypeId", "FacilityTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OmbudsmanDb.FacilityType), "Facilities", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OmbudsmanDb.Facility), true)]
[assembly: EdmRelationshipAttribute("OmbudsmanModel", "FK_dbo_Facilities_dbo_Ombudsmen_OmbudsmanId", "Ombudsmen", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(OmbudsmanDb.Ombudsman), "Facilities", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OmbudsmanDb.Facility), true)]

#endregion

namespace OmbudsmanDb
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OmbudsmanEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OmbudsmanEntities object using the connection string found in the 'OmbudsmanEntities' section of the application configuration file.
        /// </summary>
        public OmbudsmanEntities() : base("name=OmbudsmanEntities", "OmbudsmanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OmbudsmanEntities object.
        /// </summary>
        public OmbudsmanEntities(string connectionString) : base(connectionString, "OmbudsmanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OmbudsmanEntities object.
        /// </summary>
        public OmbudsmanEntities(EntityConnection connection) : base(connection, "OmbudsmanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Facility> Facilities
        {
            get
            {
                if ((_Facilities == null))
                {
                    _Facilities = base.CreateObjectSet<Facility>("Facilities");
                }
                return _Facilities;
            }
        }
        private ObjectSet<Facility> _Facilities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FacilityType> FacilityTypes
        {
            get
            {
                if ((_FacilityTypes == null))
                {
                    _FacilityTypes = base.CreateObjectSet<FacilityType>("FacilityTypes");
                }
                return _FacilityTypes;
            }
        }
        private ObjectSet<FacilityType> _FacilityTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ombudsman> Ombudsmen
        {
            get
            {
                if ((_Ombudsmen == null))
                {
                    _Ombudsmen = base.CreateObjectSet<Ombudsman>("Ombudsmen");
                }
                return _Ombudsmen;
            }
        }
        private ObjectSet<Ombudsman> _Ombudsmen;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Facilities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFacilities(Facility facility)
        {
            base.AddObject("Facilities", facility);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FacilityTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFacilityTypes(FacilityType facilityType)
        {
            base.AddObject("FacilityTypes", facilityType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ombudsmen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOmbudsmen(Ombudsman ombudsman)
        {
            base.AddObject("Ombudsmen", ombudsman);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<TestInitialize_Result> TestInitialize()
        {
            return base.ExecuteFunction<TestInitialize_Result>("TestInitialize");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OmbudsmanModel", Name="Facility")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Facility : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Facility object.
        /// </summary>
        /// <param name="facilityId">Initial value of the FacilityId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="facilityTypeId">Initial value of the FacilityTypeId property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Facility CreateFacility(global::System.Int32 facilityId, global::System.String name, global::System.Int32 facilityTypeId, global::System.Boolean isActive)
        {
            Facility facility = new Facility();
            facility.FacilityId = facilityId;
            facility.Name = name;
            facility.FacilityTypeId = facilityTypeId;
            facility.IsActive = isActive;
            return facility;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FacilityId
        {
            get
            {
                return _FacilityId;
            }
            set
            {
                if (_FacilityId != value)
                {
                    OnFacilityIdChanging(value);
                    ReportPropertyChanging("FacilityId");
                    _FacilityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FacilityId");
                    OnFacilityIdChanged();
                }
            }
        }
        private global::System.Int32 _FacilityId;
        partial void OnFacilityIdChanging(global::System.Int32 value);
        partial void OnFacilityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FacilityTypeId
        {
            get
            {
                return _FacilityTypeId;
            }
            set
            {
                OnFacilityTypeIdChanging(value);
                ReportPropertyChanging("FacilityTypeId");
                _FacilityTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacilityTypeId");
                OnFacilityTypeIdChanged();
            }
        }
        private global::System.Int32 _FacilityTypeId;
        partial void OnFacilityTypeIdChanging(global::System.Int32 value);
        partial void OnFacilityTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OmbudsmanId
        {
            get
            {
                return _OmbudsmanId;
            }
            set
            {
                OnOmbudsmanIdChanging(value);
                ReportPropertyChanging("OmbudsmanId");
                _OmbudsmanId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OmbudsmanId");
                OnOmbudsmanIdChanged();
            }
        }
        private Nullable<global::System.Int32> _OmbudsmanId;
        partial void OnOmbudsmanIdChanging(Nullable<global::System.Int32> value);
        partial void OnOmbudsmanIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.String _ZipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumberOfBeds
        {
            get
            {
                return _NumberOfBeds;
            }
            set
            {
                OnNumberOfBedsChanging(value);
                ReportPropertyChanging("NumberOfBeds");
                _NumberOfBeds = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfBeds");
                OnNumberOfBedsChanged();
            }
        }
        private Nullable<global::System.Int32> _NumberOfBeds;
        partial void OnNumberOfBedsChanging(Nullable<global::System.Int32> value);
        partial void OnNumberOfBedsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsMedicaid
        {
            get
            {
                return _IsMedicaid;
            }
            set
            {
                OnIsMedicaidChanging(value);
                ReportPropertyChanging("IsMedicaid");
                _IsMedicaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMedicaid");
                OnIsMedicaidChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsMedicaid;
        partial void OnIsMedicaidChanging(Nullable<global::System.Boolean> value);
        partial void OnIsMedicaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsContinuum
        {
            get
            {
                return _IsContinuum;
            }
            set
            {
                OnIsContinuumChanging(value);
                ReportPropertyChanging("IsContinuum");
                _IsContinuum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsContinuum");
                OnIsContinuumChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsContinuum;
        partial void OnIsContinuumChanging(Nullable<global::System.Boolean> value);
        partial void OnIsContinuumChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OmbudsmanModel", "FK_dbo_Facilities_dbo_FacilityTypes_FacilityTypeId", "FacilityTypes")]
        public FacilityType FacilityType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FacilityType>("OmbudsmanModel.FK_dbo_Facilities_dbo_FacilityTypes_FacilityTypeId", "FacilityTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FacilityType>("OmbudsmanModel.FK_dbo_Facilities_dbo_FacilityTypes_FacilityTypeId", "FacilityTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FacilityType> FacilityTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FacilityType>("OmbudsmanModel.FK_dbo_Facilities_dbo_FacilityTypes_FacilityTypeId", "FacilityTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FacilityType>("OmbudsmanModel.FK_dbo_Facilities_dbo_FacilityTypes_FacilityTypeId", "FacilityTypes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OmbudsmanModel", "FK_dbo_Facilities_dbo_Ombudsmen_OmbudsmanId", "Ombudsmen")]
        public Ombudsman Ombudsman
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ombudsman>("OmbudsmanModel.FK_dbo_Facilities_dbo_Ombudsmen_OmbudsmanId", "Ombudsmen").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ombudsman>("OmbudsmanModel.FK_dbo_Facilities_dbo_Ombudsmen_OmbudsmanId", "Ombudsmen").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ombudsman> OmbudsmanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ombudsman>("OmbudsmanModel.FK_dbo_Facilities_dbo_Ombudsmen_OmbudsmanId", "Ombudsmen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ombudsman>("OmbudsmanModel.FK_dbo_Facilities_dbo_Ombudsmen_OmbudsmanId", "Ombudsmen", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OmbudsmanModel", Name="FacilityType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FacilityType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FacilityType object.
        /// </summary>
        /// <param name="facilityTypeId">Initial value of the FacilityTypeId property.</param>
        public static FacilityType CreateFacilityType(global::System.Int32 facilityTypeId)
        {
            FacilityType facilityType = new FacilityType();
            facilityType.FacilityTypeId = facilityTypeId;
            return facilityType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FacilityTypeId
        {
            get
            {
                return _FacilityTypeId;
            }
            set
            {
                if (_FacilityTypeId != value)
                {
                    OnFacilityTypeIdChanging(value);
                    ReportPropertyChanging("FacilityTypeId");
                    _FacilityTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FacilityTypeId");
                    OnFacilityTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _FacilityTypeId;
        partial void OnFacilityTypeIdChanging(global::System.Int32 value);
        partial void OnFacilityTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OmbudsmanModel", "FK_dbo_Facilities_dbo_FacilityTypes_FacilityTypeId", "Facilities")]
        public EntityCollection<Facility> Facilities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Facility>("OmbudsmanModel.FK_dbo_Facilities_dbo_FacilityTypes_FacilityTypeId", "Facilities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Facility>("OmbudsmanModel.FK_dbo_Facilities_dbo_FacilityTypes_FacilityTypeId", "Facilities", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OmbudsmanModel", Name="Ombudsman")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ombudsman : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ombudsman object.
        /// </summary>
        /// <param name="ombudsmanId">Initial value of the OmbudsmanId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        public static Ombudsman CreateOmbudsman(global::System.Int32 ombudsmanId, global::System.String name, global::System.String userName)
        {
            Ombudsman ombudsman = new Ombudsman();
            ombudsman.OmbudsmanId = ombudsmanId;
            ombudsman.Name = name;
            ombudsman.UserName = userName;
            return ombudsman;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OmbudsmanId
        {
            get
            {
                return _OmbudsmanId;
            }
            set
            {
                if (_OmbudsmanId != value)
                {
                    OnOmbudsmanIdChanging(value);
                    ReportPropertyChanging("OmbudsmanId");
                    _OmbudsmanId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OmbudsmanId");
                    OnOmbudsmanIdChanged();
                }
            }
        }
        private global::System.Int32 _OmbudsmanId;
        partial void OnOmbudsmanIdChanging(global::System.Int32 value);
        partial void OnOmbudsmanIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.String _ZipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OmbudsmanModel", "FK_dbo_Facilities_dbo_Ombudsmen_OmbudsmanId", "Facilities")]
        public EntityCollection<Facility> Facilities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Facility>("OmbudsmanModel.FK_dbo_Facilities_dbo_Ombudsmen_OmbudsmanId", "Facilities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Facility>("OmbudsmanModel.FK_dbo_Facilities_dbo_Ombudsmen_OmbudsmanId", "Facilities", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="OmbudsmanModel", Name="TestInitialize_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class TestInitialize_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Facility1
        {
            get
            {
                return _Facility1;
            }
            set
            {
                OnFacility1Changing(value);
                ReportPropertyChanging("Facility1");
                _Facility1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Facility1");
                OnFacility1Changed();
            }
        }
        private Nullable<global::System.Int32> _Facility1;
        partial void OnFacility1Changing(Nullable<global::System.Int32> value);
        partial void OnFacility1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ombudsman1
        {
            get
            {
                return _Ombudsman1;
            }
            set
            {
                OnOmbudsman1Changing(value);
                ReportPropertyChanging("Ombudsman1");
                _Ombudsman1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ombudsman1");
                OnOmbudsman1Changed();
            }
        }
        private Nullable<global::System.Int32> _Ombudsman1;
        partial void OnOmbudsman1Changing(Nullable<global::System.Int32> value);
        partial void OnOmbudsman1Changed();

        #endregion
    }

    #endregion
    
}
