//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ModelGen.Models
{
    public partial class Facility
    {
        public int FacilityId { get; set; }
        public string Name { get; set; }
        public int FacilityTypeId { get; set; }
        public Nullable<int> OmbudsmanId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> NumberOfBeds { get; set; }
        public Nullable<bool> IsMedicaid { get; set; }
        public Nullable<bool> IsContinuum { get; set; }
    
        public virtual FacilityType FacilityType { get; set; }
        public virtual Ombudsman Ombudsman { get; set; }
    }
    
}
