//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ModelGen.Models
{
    public partial class FacilityType
    {
        public FacilityType()
        {
            this.Facilities = new HashSet<Facility>();
        }
    
        public int FacilityTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Facility> Facilities { get; set; }
    }
    
}
